<?php

namespace ContainerOWUGhuh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YQvaylService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y_Qvayl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y_Qvayl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'travelPreferencesRepository' => ['privates', 'App\\Repository\\TravelPreferencesRepository', 'getTravelPreferencesRepositoryService', true],
            'trip' => ['privates', '.errored..service_locator.Y_Qvayl.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.Y_Qvayl": it references class "App\\Entity\\Trip" but no such service exists.'],
            'userExperienceLevelRepository' => ['privates', 'App\\Repository\\UserExperienceLevelRepository', 'getUserExperienceLevelRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'vehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'travelPreferencesRepository' => 'App\\Repository\\TravelPreferencesRepository',
            'trip' => 'App\\Entity\\Trip',
            'userExperienceLevelRepository' => 'App\\Repository\\UserExperienceLevelRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'vehiculeRepository' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
