<?php

namespace ContainerUUQScC3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5YGgH5OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5YGgH5O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5YGgH5O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'travelPreferencesController' => ['services', 'App\\Controller\\TravelPreferencesController', 'getTravelPreferencesControllerService', true],
            'travelPreferencesRepository' => ['privates', 'App\\Repository\\TravelPreferencesRepository', 'getTravelPreferencesRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.5YGgH5O.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.5YGgH5O": it references class "App\\Entity\\User" but no such service exists.'],
            'vehiculeController' => ['services', 'App\\Controller\\VehiculeController', 'getVehiculeControllerService', true],
            'vehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'passwordEncoder' => '?',
            'slugger' => '?',
            'travelPreferencesController' => 'App\\Controller\\TravelPreferencesController',
            'travelPreferencesRepository' => 'App\\Repository\\TravelPreferencesRepository',
            'user' => 'App\\Entity\\User',
            'vehiculeController' => 'App\\Controller\\VehiculeController',
            'vehiculeRepository' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
