<?php

namespace ContainerAMxXI6g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8K6Zguj.App\Entity\Trip' shared service.
     *
     * @return \App\Entity\Trip
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8K6Zguj": it references class "App\\Entity\\Trip" but no such service exists.');
    }
}
