<?php

namespace ContainerEZMEqV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HT72DTzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HT72DTz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HT72DTz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailerInterface' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'mailerInterface' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
