<?php

namespace ContainerQpId7eI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ECYzlTrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eCYzlTr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eCYzlTr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'travelPreferencesController' => ['services', 'App\\Controller\\TravelPreferencesController', 'getTravelPreferencesControllerService', true],
            'travelPreferencesRepository' => ['privates', 'App\\Repository\\TravelPreferencesRepository', 'getTravelPreferencesRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.eCYzlTr.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.eCYzlTr": it references class "App\\Entity\\User" but no such service exists.'],
            'vehiculeController' => ['services', 'App\\Controller\\VehiculeController', 'getVehiculeControllerService', true],
            'vehiculeType' => ['privates', 'App\\Form\\VehiculeType', 'getVehiculeTypeService', true],
        ], [
            'slugger' => '?',
            'travelPreferencesController' => 'App\\Controller\\TravelPreferencesController',
            'travelPreferencesRepository' => 'App\\Repository\\TravelPreferencesRepository',
            'user' => 'App\\Entity\\User',
            'vehiculeController' => 'App\\Controller\\VehiculeController',
            'vehiculeType' => 'App\\Form\\VehiculeType',
        ]);
    }
}
