<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2CcDoH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2CcDoH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerO2CcDoH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerO2CcDoH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerO2CcDoH\App_KernelProdContainer([
    'container.build_hash' => 'O2CcDoH',
    'container.build_id' => '4144c647',
    'container.build_time' => 1632833898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2CcDoH');
