<?php

namespace ContainerDrbX9Ul;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6rc6rfLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6rc6rfL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6rc6rfL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeOfVehiculeRepository' => ['privates', 'App\\Repository\\TypeOfVehiculeRepository', 'getTypeOfVehiculeRepositoryService', true],
        ], [
            'typeOfVehiculeRepository' => 'App\\Repository\\TypeOfVehiculeRepository',
        ]);
    }
}
