<?php

namespace ContainerDrbX9Ul;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vkb0lezService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vkb0lez' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vkb0lez'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.Vkb0lez.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Vkb0lez": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
