<?php

namespace ContainerDrbX9Ul;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQgW0RKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kQgW0RK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kQgW0RK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trip' => ['privates', '.errored..service_locator.kQgW0RK.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.kQgW0RK": it references class "App\\Entity\\Trip" but no such service exists.'],
            'userExperienceLevelRepository' => ['privates', 'App\\Repository\\UserExperienceLevelRepository', 'getUserExperienceLevelRepositoryService', true],
        ], [
            'trip' => 'App\\Entity\\Trip',
            'userExperienceLevelRepository' => 'App\\Repository\\UserExperienceLevelRepository',
        ]);
    }
}
