<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehicule extends \App\Entity\Vehicule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'country_of_registration', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'numberplate', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'color', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'year', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'vehicule_picture', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'typeOfVehicule'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'country_of_registration', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'numberplate', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'color', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'year', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'vehicule_picture', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'typeOfVehicule'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehicule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryOfRegistration(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryOfRegistration', []);

        return parent::getCountryOfRegistration();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryOfRegistration(?string $country_of_registration): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryOfRegistration', [$country_of_registration]);

        return parent::setCountryOfRegistration($country_of_registration);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberplate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberplate', []);

        return parent::getNumberplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberplate(?string $numberplate): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberplate', [$numberplate]);

        return parent::setNumberplate($numberplate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(?string $brand): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', []);

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(?string $model): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', [$model]);

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor(?string $color): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear(?int $year): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiculePicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiculePicture', []);

        return parent::getVehiculePicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiculePicture(?string $vehicule_picture): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiculePicture', [$vehicule_picture]);

        return parent::setVehiculePicture($vehicule_picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeOfVehicule(): ?\App\Entity\TypeOfVehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeOfVehicule', []);

        return parent::getTypeOfVehicule();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeOfVehicule(?\App\Entity\TypeOfVehicule $typeOfVehicule): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeOfVehicule', [$typeOfVehicule]);

        return parent::setTypeOfVehicule($typeOfVehicule);
    }

}
