<?php

namespace ContainerO2CcDoH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravelPreferencesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TravelPreferencesType' shared autowired service.
     *
     * @return \App\Form\TravelPreferencesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TravelPreferencesType'] = new \App\Form\TravelPreferencesType();
    }
}
