<?php

namespace ContainerO2CcDoH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeOfVehiculeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TypeOfVehiculeRepository' shared autowired service.
     *
     * @return \App\Repository\TypeOfVehiculeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TypeOfVehiculeRepository'] = new \App\Repository\TypeOfVehiculeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
