<?php

namespace ContainerHnoafoZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravelPreferencesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JUZyQIf.App\Entity\TravelPreferences' shared service.
     *
     * @return \App\Entity\TravelPreferences
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JUZyQIf": it references class "App\\Entity\\TravelPreferences" but no such service exists.');
    }
}
