<?php

namespace ContainerOkWOYQw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GRzSib0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GRzSib0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GRzSib0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userContacted' => ['privates', '.errored..service_locator.GRzSib0.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.GRzSib0": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'userContacted' => 'App\\Entity\\User',
        ]);
    }
}
