<?php

namespace ContainerNfi0PWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qs7d6iWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qs7d6iW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qs7d6iW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tokenStorage' => ['privates', '.errored..service_locator.qs7d6iW.Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage', NULL, 'Cannot autowire service ".service_locator.qs7d6iW": it references class "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage" but no such service exists. Try changing the type-hint to "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface" instead.'],
            'travelPreferencesRepository' => ['privates', 'App\\Repository\\TravelPreferencesRepository', 'getTravelPreferencesRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.qs7d6iW.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.qs7d6iW": it references class "App\\Entity\\User" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'vehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'tokenStorage' => 'Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage',
            'travelPreferencesRepository' => 'App\\Repository\\TravelPreferencesRepository',
            'user' => 'App\\Entity\\User',
            'userRepository' => 'App\\Repository\\UserRepository',
            'vehiculeRepository' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
