<?php

namespace ContainerNfi0PWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTokenStorageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qs7d6iW.Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qs7d6iW": it references class "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorage" but no such service exists. Try changing the type-hint to "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface" instead.');
    }
}
