<?php

namespace ContainerVHsKfKO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeOfVehiculeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.W8c9CE7.App\Entity\TypeOfVehicule' shared service.
     *
     * @return \App\Entity\TypeOfVehicule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.W8c9CE7": it references class "App\\Entity\\TypeOfVehicule" but no such service exists.');
    }
}
