<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnr8PJq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnr8PJq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCnr8PJq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCnr8PJq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCnr8PJq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cnr8PJq',
    'container.build_id' => 'ab50c082',
    'container.build_time' => 1631866038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnr8PJq');
