<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkWOYQw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkWOYQw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOkWOYQw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOkWOYQw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOkWOYQw\App_KernelDevDebugContainer([
    'container.build_hash' => 'OkWOYQw',
    'container.build_id' => '66269f97',
    'container.build_time' => 1632490831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkWOYQw');
