<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS7T6fy7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS7T6fy7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS7T6fy7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS7T6fy7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS7T6fy7\App_KernelDevDebugContainer([
    'container.build_hash' => 'S7T6fy7',
    'container.build_id' => '4ee0f1f6',
    'container.build_time' => 1632400272,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS7T6fy7');
