<?php

namespace ContainerBpneZ0g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YkGnSd_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ykGnSd.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ykGnSd.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRated' => ['privates', '.errored..service_locator.ykGnSd..App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.ykGnSd.": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'userRated' => 'App\\Entity\\User',
        ]);
    }
}
